name: mufahh
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  image_picker: ^0.8.6
  carousel_slider: ^4.1.1
  dropdown_search: ^3.0.1
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  firebase_core: ^2.3.0
  date_time_picker: ^2.1.0
  fluttertoast: ^8.1.2
  share_plus: ^4.0.10+1
  # webview_flutter_plus: ^0.3.0+2
  url_launcher: ^6.1.10
  # geocoder: ^0.2.1
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  expansion_card: ^0.1.0
  # location: ^4.4.0
  # google_maps_flutter: ^2.2.5
  # webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/Images/
   - assets/icon/

